// 启用AndroidX
android.useAndroidX=true

// 启用Jetifier以自动迁移第三方库到AndroidX
android.enableJetifier=true

// 抑制compileSdk 34不被支持的警告
android.suppressUnsupportedCompileSdk=34

// 启用Gradle的并行构建以提高构建速度
org.gradle.parallel=true

// 启用Gradle的构建缓存
org.gradle.caching=true

// 增加Gradle的内存大小
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

// 指定JVM版本要求
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true